### PR TITLE
regex to filter comments in authorized_keys file not working

### PR DESCRIPTION
**Pull request by databus23**

### CODE REVIEW

**Comment by jordansissel** [comment]
sshkeyauth 0.0.10 pushed to rubygems. Thanks!

**Comment by databus23** [comment]
Are you sure it was pushed to rubygems? http://rubygems.org/gems/sshkeyauth-0.0.10.gem still contains the bug.  I have no experience with publishing gems to rubygems but maybe you can't update a gem without bumping the version numer?

**Comment by jordansissel** [comment]
Pretty sure I pulled it in before releasing, here's the commits from 'git log':

```
commit 4df7f1123205f120b8f2e3cedcecb9f9e6c9c23b
Author: Jordan Sissel <jls@semicomplete.com>
Date:   Sun Aug 21 21:36:48 2011 -0700

    - bump version

commit e88b297b3e193cb49a85ba41f74f1de67b78422e
Merge: 10a388a 83f1c3f
Author: Jordan Sissel <jls@semicomplete.com>
Date:   Sun Aug 21 21:35:49 2011 -0700

    Merge pull request #1 from databus23/master

    regex to filter comments in authorized_keys file not working
```

**Comment by databus23** [comment]
But the gem from http://rubygems.org/downloads/sshkeyauth-0.0.10.gem still contains the bug:

```
wget http://rubygems.org/downloads/sshkeyauth-0.0.10.gem
gem unpack sshkeyauth-0.0.10.gem
grep 'Skip comments' sshkeyauth-0.0.10/lib/ssh/key/verifier.rb
```

I also don't see how the version was bumped. It was 0.0.10 on github since May 10, 2011 (http://rubygems.org/gems/sshkeyauth/versions)

**Comment by jordansissel** [comment]
Confrmed I just downloaded it from rubygems and checked. I'll push 0.0.11, oops! ;)

**Comment by jordansissel** [comment]
Should be really fixed now :)

```
% gem fetch sshkeyauth
Fetching: sshkeyauth-0.0.11.gem (100%)
Downloaded sshkeyauth-0.0.11
% gem unpack sshkeyauth-0.0.11.gem
Unpacked gem: '/tmp/sshkeyauth-0.0.11'
% cd sshkeyauth-0.0.11
% ls
lib/  samples/
% !ack
ack 'Skip comments'
lib/ssh/key/verifier.rb
203:      next if line =~ /^\s*\#/  # Skip comments
```

**Pull request merged**
